In [ ]:
import numpy as np
import pandas as pd

In [ ]:
#making data frames using dictinary
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [ ]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2 = pd.DataFrame(data_list)
columns = ["Name","Age","City","Salary"]
df2 = pd.DataFrame(data_list,columns=columns)
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
Selection and Indexing of Columns

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#for selecting only one column or series
df2['Name']

0     John
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

0    28
1    34
2    29
3    42
Name: Age, dtype: int64

    Name  Age
0   John   28
1   Anna   34
2  Peter   29
3  Linda   42

    Name  Age      City  Salary Designation
0   John   28  New York   65000          HR
1   Anna   34     Paris   70000    ACCOUNTS
2  Peter   29    Berlin   62000          QC
3  Linda   42    London   85000          QA

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

    Name      City
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

    Name  Age    City  Salary
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

   Name  Age      City  Salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

       City  Salary
0  New York   65000
1     Paris   70000

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

   Name  Age   City  Salary
1  Anna   34  Paris   70000