,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount
0,1001,C001,Male,22,Karachi,Laptop,Electronics,120000,1,05/01/2025,Credit Card,4,10
1,1002,C002,Female,25,Lahore,Headphones,Electronics,5000,2,07/01/2025,Cash,5,5
2,1003,C003,Male,30,Islamabad,Shirt,Fashion,2500,3,08/01/2025,Debit Card,3,15
3,1004,C004,Female,28,Karachi,Shoes,Fashion,7000,1,09/01/2025,EasyPaisa,4,20
4,1005,C005,Male,35,Peshawar,Mobile,Electronics,80000,1,10/01/2025,Credit Card,5,8
5,1006,C006,Female,19,Quetta,Bag,Fashion,3000,2,11/01/2025,JazzCash,3,12
6,1007,C007,Male,40,Karachi,TV,Electronics,150000,1,12/01/2025,Cash,4,18
7,1008,C008,Female,27,Lahore,Watch,Accessories,10000,1,13/01/2025,Debit Card,5,10
8,1009,C009,Male,31,Islamabad,Keyboard,Electronics,3500,2,14/01/2025,Credit Card,4,5
9,1010,C010,Female,23,Karachi,Makeup Kit,Beauty,4500,1,15/01/2025,EasyPaisa,5,20
10,1011,C011,Male,29,Multan,Shoes,Fashion,6500,2,16/01/2025,Cash,3,15
11,1012,C012,Female,33,Lahore,Perfume,Beauty,8000,1,17/01/2025,Credit Card,4,10
12,1013,C013,Male,26,Karachi,Mouse,Electronics,2000,3,18/01/2025,JazzCash,4,5
13,1014,C014,Female,21,Islamabad,Dress,Fashion,9000,1,19/01/2025,Debit Card,5,25
14,1015,C015,Male,45,Quetta,Fridge,Appliances,120000,1,20/01/2025,Credit Card,4,12
15,1016,C016,Female,38,Peshawar,Oven,Appliances,50000,1,21/01/2025,Cash,3,10
16,1017,C017,Male,24,Karachi,T-shirt,Fashion,1500,4,22/01/2025,EasyPaisa,5,5
17,1018,C018,Female,29,Lahore,Tablet,Electronics,60000,1,23/01/2025,Credit Card,4,10
18,1019,C019,Male,32,Islamabad,Camera,Electronics,95000,1,24/01/2025,Debit Card,5,15
19,1020,C020,Female,26,Karachi,Handbag,Accessories,7000,1,25/01/2025,JazzCash,4,18
20,1021,C021,Male,34,Multan,Sneakers,Fashion,8500,2,26/01/2025,Cash,3,10
21,1022,C022,Female,28,Quetta,Lipstick,Beauty,2000,3,27/01/2025,EasyPaisa,5,20
22,1023,C023,Male,41,Karachi,Air Conditioner,Appliances,180000,1,28/01/2025,Credit Card,4,15
23,1024,C024,Female,22,Lahore,Scarf,Fashion,1200,2,29/01/2025,Debit Card,4,5
24,1025,C025,Male,37,Islamabad,Speaker,Electronics,9000,1,30/01/2025,Cash,5,10

(25, 13)

Index(['OrderID', 'CustomerID', 'Gender', 'Age', 'City', 'Product', 'Category',
       'Price', 'Quantity', 'OrderDate', 'PaymentMethod', 'Rating',
       'Discount'],
      dtype='object')

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount
0,1001,C001,Male,22,Karachi,Laptop,Electronics,120000,1,05/01/2025,Credit Card,4,10
1,1002,C002,Female,25,Lahore,Headphones,Electronics,5000,2,07/01/2025,Cash,5,5
2,1003,C003,Male,30,Islamabad,Shirt,Fashion,2500,3,08/01/2025,Debit Card,3,15
3,1004,C004,Female,28,Karachi,Shoes,Fashion,7000,1,09/01/2025,EasyPaisa,4,20
4,1005,C005,Male,35,Peshawar,Mobile,Electronics,80000,1,10/01/2025,Credit Card,5,8
5,1006,C006,Female,19,Quetta,Bag,Fashion,3000,2,11/01/2025,JazzCash,3,12
6,1007,C007,Male,40,Karachi,TV,Electronics,150000,1,12/01/2025,Cash,4,18
7,1008,C008,Female,27,Lahore,Watch,Accessories,10000,1,13/01/2025,Debit Card,5,10
8,1009,C009,Male,31,Islamabad,Keyboard,Electronics,3500,2,14/01/2025,Credit Card,4,5
9,1010,C010,Female,23,Karachi,Makeup Kit,Beauty,4500,1,15/01/2025,EasyPaisa,5,20

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderID        25 non-null     int64
 1   CustomerID     25 non-null     object
 2   Gender         25 non-null     object
 3   Age            25 non-null     int64
 4   City           25 non-null     object
 5   Product        25 non-null     object
 6   Category       25 non-null     object
 7   Price          25 non-null     int64
 8   Quantity       25 non-null     int64
 9   OrderDate      25 non-null     object
 10  PaymentMethod  25 non-null     object
 11  Rating         25 non-null     int64
 12  Discount       25 non-null     int64
dtypes: int64(6), object(7)
memory usage: 2.7+ KB

City
Karachi      8
Lahore       5
Islamabad    5
Quetta       3
Peshawar     2
Multan       2
Name: count, dtype: int64

City
Karachi      8
Lahore       5
Islamabad    5
Quetta       3
Peshawar     2
Multan       2
Name: count, dtype: int64

29

0     120000
1      10000
2       7500
3       7000
4      80000
5       6000
6     150000
7      10000
8       7000
9       4500
10     13000
11      8000
12      6000
13      9000
14    120000
15     50000
16      6000
17     60000
18     95000
19      7000
20     17000
21      6000
22    180000
23      2400
24      9000
dtype: int64

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount,Totalrevenue
16,1017,C017,Male,24,Karachi,T-shirt,Fashion,1500,4,22/01/2025,EasyPaisa,5,5,6000
12,1013,C013,Male,26,Karachi,Mouse,Electronics,2000,3,18/01/2025,JazzCash,4,5,6000
2,1003,C003,Male,30,Islamabad,Shirt,Fashion,2500,3,08/01/2025,Debit Card,3,15,7500
21,1022,C022,Female,28,Quetta,Lipstick,Beauty,2000,3,27/01/2025,EasyPaisa,5,20,6000
23,1024,C024,Female,22,Lahore,Scarf,Fashion,1200,2,29/01/2025,Debit Card,4,5,2400
5,1006,C006,Female,19,Quetta,Bag,Fashion,3000,2,11/01/2025,JazzCash,3,12,6000
20,1021,C021,Male,34,Multan,Sneakers,Fashion,8500,2,26/01/2025,Cash,3,10,17000
8,1009,C009,Male,31,Islamabad,Keyboard,Electronics,3500,2,14/01/2025,Credit Card,4,5,7000
10,1011,C011,Male,29,Multan,Shoes,Fashion,6500,2,16/01/2025,Cash,3,15,13000
1,1002,C002,Female,25,Lahore,Headphones,Electronics,5000,2,07/01/2025,Cash,5,5,10000
15,1016,C016,Female,38,Peshawar,Oven,Appliances,50000,1,21/01/2025,Cash,3,10,50000
22,1023,C023,Male,41,Karachi,Air Conditioner,Appliances,180000,1,28/01/2025,Credit Card,4,15,180000
19,1020,C020,Female,26,Karachi,Handbag,Accessories,7000,1,25/01/2025,JazzCash,4,18,7000
18,1019,C019,Male,32,Islamabad,Camera,Electronics,95000,1,24/01/2025,Debit Card,5,15,95000
17,1018,C018,Female,29,Lahore,Tablet,Electronics,60000,1,23/01/2025,Credit Card,4,10,60000
0,1001,C001,Male,22,Karachi,Laptop,Electronics,120000,1,05/01/2025,Credit Card,4,10,120000
14,1015,C015,Male,45,Quetta,Fridge,Appliances,120000,1,20/01/2025,Credit Card,4,12,120000
13,1014,C014,Female,21,Islamabad,Dress,Fashion,9000,1,19/01/2025,Debit Card,5,25,9000
11,1012,C012,Female,33,Lahore,Perfume,Beauty,8000,1,17/01/2025,Credit Card,4,10,8000
9,1010,C010,Female,23,Karachi,Makeup Kit,Beauty,4500,1,15/01/2025,EasyPaisa,5,20,4500
7,1008,C008,Female,27,Lahore,Watch,Accessories,10000,1,13/01/2025,Debit Card,5,10,10000
6,1007,C007,Male,40,Karachi,TV,Electronics,150000,1,12/01/2025,Cash,4,18,150000
4,1005,C005,Male,35,Peshawar,Mobile,Electronics,80000,1,10/01/2025,Credit Card,5,8,80000
3,1004,C004,Female,28,Karachi,Shoes,Fashion,7000,1,09/01/2025,EasyPaisa,4,20,7000
24,1025,C025,Male,37,Islamabad,Speaker,Electronics,9000,1,30/01/2025,Cash,5,10,9000

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount
16,1017,C017,Male,24,Karachi,T-shirt,Fashion,1500,4,22/01/2025,EasyPaisa,5,5
12,1013,C013,Male,26,Karachi,Mouse,Electronics,2000,3,18/01/2025,JazzCash,4,5
2,1003,C003,Male,30,Islamabad,Shirt,Fashion,2500,3,08/01/2025,Debit Card,3,15
21,1022,C022,Female,28,Quetta,Lipstick,Beauty,2000,3,27/01/2025,EasyPaisa,5,20
23,1024,C024,Female,22,Lahore,Scarf,Fashion,1200,2,29/01/2025,Debit Card,4,5

Category
Electronics    9
Fashion        8
Beauty         3
Appliances     3
Accessories    2
Name: count, dtype: int64

MALE COUNT IS 13 & FEMALE COUNT IS 12

Category
Accessories    4.500000
Appliances     3.666667
Beauty         4.666667
Electronics    4.444444
Fashion        3.750000
Name: Rating, dtype: float64

City
Islamabad    127500
Karachi      480500
Lahore        90400
Multan        30000
Peshawar     130000
Quetta       132000
Name: Totalrevenue, dtype: int64

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount,Totalrevenue
22,1023,C023,Male,41,Karachi,Air Conditioner,Appliances,180000,1,28/01/2025,Credit Card,4,15,180000
6,1007,C007,Male,40,Karachi,TV,Electronics,150000,1,12/01/2025,Cash,4,18,150000
14,1015,C015,Male,45,Quetta,Fridge,Appliances,120000,1,20/01/2025,Credit Card,4,12,120000
0,1001,C001,Male,22,Karachi,Laptop,Electronics,120000,1,05/01/2025,Credit Card,4,10,120000
18,1019,C019,Male,32,Islamabad,Camera,Electronics,95000,1,24/01/2025,Debit Card,5,15,95000
4,1005,C005,Male,35,Peshawar,Mobile,Electronics,80000,1,10/01/2025,Credit Card,5,8,80000
17,1018,C018,Female,29,Lahore,Tablet,Electronics,60000,1,23/01/2025,Credit Card,4,10,60000
15,1016,C016,Female,38,Peshawar,Oven,Appliances,50000,1,21/01/2025,Cash,3,10,50000
7,1008,C008,Female,27,Lahore,Watch,Accessories,10000,1,13/01/2025,Debit Card,5,10,10000
24,1025,C025,Male,37,Islamabad,Speaker,Electronics,9000,1,30/01/2025,Cash,5,10,9000
13,1014,C014,Female,21,Islamabad,Dress,Fashion,9000,1,19/01/2025,Debit Card,5,25,9000
20,1021,C021,Male,34,Multan,Sneakers,Fashion,8500,2,26/01/2025,Cash,3,10,17000
11,1012,C012,Female,33,Lahore,Perfume,Beauty,8000,1,17/01/2025,Credit Card,4,10,8000
3,1004,C004,Female,28,Karachi,Shoes,Fashion,7000,1,09/01/2025,EasyPaisa,4,20,7000
19,1020,C020,Female,26,Karachi,Handbag,Accessories,7000,1,25/01/2025,JazzCash,4,18,7000
10,1011,C011,Male,29,Multan,Shoes,Fashion,6500,2,16/01/2025,Cash,3,15,13000
1,1002,C002,Female,25,Lahore,Headphones,Electronics,5000,2,07/01/2025,Cash,5,5,10000
9,1010,C010,Female,23,Karachi,Makeup Kit,Beauty,4500,1,15/01/2025,EasyPaisa,5,20,4500
8,1009,C009,Male,31,Islamabad,Keyboard,Electronics,3500,2,14/01/2025,Credit Card,4,5,7000
5,1006,C006,Female,19,Quetta,Bag,Fashion,3000,2,11/01/2025,JazzCash,3,12,6000
2,1003,C003,Male,30,Islamabad,Shirt,Fashion,2500,3,08/01/2025,Debit Card,3,15,7500
12,1013,C013,Male,26,Karachi,Mouse,Electronics,2000,3,18/01/2025,JazzCash,4,5,6000
21,1022,C022,Female,28,Quetta,Lipstick,Beauty,2000,3,27/01/2025,EasyPaisa,5,20,6000
16,1017,C017,Male,24,Karachi,T-shirt,Fashion,1500,4,22/01/2025,EasyPaisa,5,5,6000
23,1024,C024,Female,22,Lahore,Scarf,Fashion,1200,2,29/01/2025,Debit Card,4,5,2400

,OrderID,CustomerID,Gender,Age,City,Product,Category,Price,Quantity,OrderDate,PaymentMethod,Rating,Discount,Totalrevenue
6,1007,C007,Male,40,Karachi,TV,Electronics,150000,1,12/01/2025,Cash,4,18,150000
13,1014,C014,Female,21,Islamabad,Dress,Fashion,9000,1,19/01/2025,Debit Card,5,25,9000
3,1004,C004,Female,28,Karachi,Shoes,Fashion,7000,1,09/01/2025,EasyPaisa,4,20,7000
19,1020,C020,Female,26,Karachi,Handbag,Accessories,7000,1,25/01/2025,JazzCash,4,18,7000
9,1010,C010,Female,23,Karachi,Makeup Kit,Beauty,4500,1,15/01/2025,EasyPaisa,5,20,4500
21,1022,C022,Female,28,Quetta,Lipstick,Beauty,2000,3,27/01/2025,EasyPaisa,5,20,6000