         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    949     19   John  January      Q1
1  2023-01-02       B   West    610     73   Mary  January      Q1
2  2023-01-03       C  North    796     28    Bob  January      Q1
3  2023-01-04       D  South    715     47  Alice  January      Q1
4  2023-01-05       A   East    271     13   John  January      Q1
5  2023-01-06       B   West    310     77   Mary  January      Q1
6  2023-01-07       C  North    230     73    Bob  January      Q1
7  2023-01-08       D  South    836     89  Alice  January      Q1
8  2023-01-09       A   East    260     32   John  January      Q1
9  2023-01-10       B   West    125     41   Mary  January      Q1
10 2023-01-11       C  North    557     77    Bob  January      Q1
11 2023-01-12       D  South    410     52  Alice  January      Q1
12 2023-01-13       A   East    716     39   John  January      Q1
13 2023-01-14       B   West    661     34   Mary  January      Q1
14 2023-01-15       C  North    668     31    Bob  January      Q1
15 2023-01-16       D  South    792     96  Alice  January      Q1
16 2023-01-17       A   East    840     97   John  January      Q1
17 2023-01-18       B   West    518     31   Mary  January      Q1
18 2023-01-19       C  North    849     21    Bob  January      Q1
19 2023-01-20       D  South    955     95  Alice  January      Q1

East
         Date Product Region  Sales  Units   Rep    Month Quarter
0  2023-01-01       A   East    949     19  John  January      Q1
4  2023-01-05       A   East    271     13  John  January      Q1
8  2023-01-09       A   East    260     32  John  January      Q1
12 2023-01-13       A   East    716     39  John  January      Q1
16 2023-01-17       A   East    840     97  John  January      Q1
North
         Date Product Region  Sales  Units  Rep    Month Quarter
2  2023-01-03       C  North    796     28  Bob  January      Q1
6  2023-01-07       C  North    230     73  Bob  January      Q1
10 2023-01-11       C  North    557     77  Bob  January      Q1
14 2023-01-15       C  North    668     31  Bob  January      Q1
18 2023-01-19       C  North    849     21  Bob  January      Q1
South
         Date Product Region  Sales  Units    Rep    Month Quarter
3  2023-01-04       D  South    715     47  Alice  January      Q1
7  2023-01-08       D  South    836     89  Alice  January      Q1
11 2023-01-12       D  South    410     52  Alice  January      Q1
15 2023-01-16       D  South    792     96  Alice  January      Q1
19 2023-01-20       D  South    955     95  Alice  January      Q1
West
         Date Product Region  Sales  Units   Rep    Month Quarter
1  2023-01-02       B   West    610     73  Mary  January      Q1
5  2023-01-06       B   West    310     77  Mary  January      Q1
9  2023-01-10       B   West    125     41  Mary  January      Q1
13 2023-01-14       B   West    661     34  Mary  January      Q1
17 2023-01-18       B   West    518     31  Mary  January      Q1

Product      A      B      C      D
Region
East     716.0    NaN    NaN    NaN
North      NaN    NaN  668.0    NaN
South      NaN    NaN    NaN  792.0
West       NaN  518.0    NaN    NaN

          Sales                          Units
Product       A       B       C       D      A      B      C      D
Region
East     3036.0     NaN     NaN     NaN  200.0    NaN    NaN    NaN
North       NaN     NaN  3100.0     NaN    NaN    NaN  230.0    NaN
South       NaN     NaN     NaN  3708.0    NaN    NaN    NaN  379.0
West        NaN  2224.0     NaN     NaN    NaN  256.0    NaN    NaN

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0